spring:
  datasource:
    url: jdbc:h2:file:./data/periodic-idle
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true