-- Тір 2: Атоми. Періодична таблиця елементів 1-36 (H..Kr), синтезованих з p+n+e.
-- Рецепт синтезу: cost_protons = atomic_number (Z), cost_electrons = Z (нейтральний атом),
-- cost_neutrons = mass_number(найпоширенішого ізотопу) - Z.
-- Приклади з CLAUDE.md: H = 1p+0n+1e, He = 2p+2n+2e.

CREATE TABLE elements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atomic_number INT NOT NULL UNIQUE,
    symbol VARCHAR(3) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    atomic_weight DOUBLE PRECISION NOT NULL,
    period INT NOT NULL,
    group_number INT NOT NULL,
    shell_config VARCHAR(30) NOT NULL,
    cost_protons BIGINT NOT NULL,
    cost_neutrons BIGINT NOT NULL,
    cost_electrons BIGINT NOT NULL
);

CREATE TABLE player_elements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    save_id BIGINT NOT NULL,
    element_id BIGINT NOT NULL,
    count BIGINT NOT NULL DEFAULT 0,
    FOREIGN KEY (save_id) REFERENCES saves(id),
    FOREIGN KEY (element_id) REFERENCES elements(id)
);

INSERT INTO elements
    (atomic_number, symbol, name, atomic_weight, period, group_number, shell_config,
     cost_protons, cost_neutrons, cost_electrons)
VALUES
    (1,  'H',  'Гідроген',  1.008,  1, 1,  '1',           1,  0,  1),
    (2,  'He', 'Гелій',     4.003,  1, 18, '2',           2,  2,  2),
    (3,  'Li', 'Літій',     6.94,   2, 1,  '2,1',         3,  4,  3),
    (4,  'Be', 'Берилій',   9.012,  2, 2,  '2,2',         4,  5,  4),
    (5,  'B',  'Бор',       10.81,  2, 13, '2,3',         5,  6,  5),
    (6,  'C',  'Карбон',    12.011, 2, 14, '2,4',         6,  6,  6),
    (7,  'N',  'Нітроген',  14.007, 2, 15, '2,5',         7,  7,  7),
    (8,  'O',  'Оксиген',   15.999, 2, 16, '2,6',         8,  8,  8),
    (9,  'F',  'Флуор',     18.998, 2, 17, '2,7',         9,  10, 9),
    (10, 'Ne', 'Неон',      20.180, 2, 18, '2,8',         10, 10, 10),
    (11, 'Na', 'Натрій',    22.990, 3, 1,  '2,8,1',       11, 12, 11),
    (12, 'Mg', 'Магній',    24.305, 3, 2,  '2,8,2',       12, 12, 12),
    (13, 'Al', 'Алюміній',  26.982, 3, 13, '2,8,3',       13, 14, 13),
    (14, 'Si', 'Силіцій',   28.085, 3, 14, '2,8,4',       14, 14, 14),
    (15, 'P',  'Фосфор',    30.974, 3, 15, '2,8,5',       15, 16, 15),
    (16, 'S',  'Сульфур',   32.06,  3, 16, '2,8,6',       16, 16, 16),
    (17, 'Cl', 'Хлор',      35.45,  3, 17, '2,8,7',       17, 18, 17),
    (18, 'Ar', 'Аргон',     39.948, 3, 18, '2,8,8',       18, 22, 18),
    (19, 'K',  'Калій',     39.098, 4, 1,  '2,8,8,1',     19, 20, 19),
    (20, 'Ca', 'Кальцій',   40.078, 4, 2,  '2,8,8,2',     20, 20, 20),
    (21, 'Sc', 'Скандій',   44.956, 4, 3,  '2,8,9,2',     21, 24, 21),
    (22, 'Ti', 'Титан',     47.867, 4, 4,  '2,8,10,2',    22, 26, 22),
    (23, 'V',  'Ванадій',   50.942, 4, 5,  '2,8,11,2',    23, 28, 23),
    (24, 'Cr', 'Хром',      51.996, 4, 6,  '2,8,13,1',    24, 28, 24),
    (25, 'Mn', 'Манган',    54.938, 4, 7,  '2,8,13,2',    25, 30, 25),
    (26, 'Fe', 'Ферум',     55.845, 4, 8,  '2,8,14,2',    26, 30, 26),
    (27, 'Co', 'Кобальт',   58.933, 4, 9,  '2,8,15,2',    27, 32, 27),
    (28, 'Ni', 'Нікель',    58.693, 4, 10, '2,8,16,2',    28, 30, 28),
    (29, 'Cu', 'Купрум',    63.546, 4, 11, '2,8,18,1',    29, 34, 29),
    (30, 'Zn', 'Цинк',      65.38,  4, 12, '2,8,18,2',    30, 34, 30),
    (31, 'Ga', 'Галій',     69.723, 4, 13, '2,8,18,3',    31, 38, 31),
    (32, 'Ge', 'Германій',  72.630, 4, 14, '2,8,18,4',    32, 42, 32),
    (33, 'As', 'Арсен',     74.922, 4, 15, '2,8,18,5',    33, 42, 33),
    (34, 'Se', 'Селен',     78.971, 4, 16, '2,8,18,6',    34, 46, 34),
    (35, 'Br', 'Бром',      79.904, 4, 17, '2,8,18,7',    35, 44, 35),
    (36, 'Kr', 'Криптон',   83.798, 4, 18, '2,8,18,8',    36, 48, 36);

-- Ініціалізуємо лічильники синтезу для save_id=1 (усі 0 — Гідроген буде першим).
INSERT INTO player_elements (save_id, element_id, count)
SELECT 1, id, 0 FROM elements;
