-- Data-driven progressive disclosure: умови розблокування тірів переносяться
-- з хардкоду фронтенду (TIER_UNLOCKS у config.js) в БД.
-- Тір розблокований, якщо ХОЧА Б ОДНА з його умов виконана (OR за рядками одного tier).
-- Для p/n/e "хоча б 1 частинка" кодується як min_log10=0 (лічильники завжди цілі >=1).

CREATE TABLE tier_unlock_conditions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier INT NOT NULL,
    resource_id BIGINT NOT NULL,
    min_log10 DOUBLE PRECISION NOT NULL,
    FOREIGN KEY (resource_id) REFERENCES resources(id)
);

-- Тір 1 (Матерія): стіна нескінченності (E >= 1e308) АБО вже є хоч одна частинка
-- (гравець міг отримати їх через престиж + обмін, не тільки колапс матерії).
INSERT INTO tier_unlock_conditions (tier, resource_id, min_log10)
SELECT 1, id, 308 FROM resources WHERE code = 'E';
INSERT INTO tier_unlock_conditions (tier, resource_id, min_log10)
SELECT 1, id, 0 FROM resources WHERE code = 'p';
INSERT INTO tier_unlock_conditions (tier, resource_id, min_log10)
SELECT 1, id, 0 FROM resources WHERE code = 'n';
INSERT INTO tier_unlock_conditions (tier, resource_id, min_log10)
SELECT 1, id, 0 FROM resources WHERE code = 'e';

-- Тір 2 (Атоми): 1000+ протонів.
INSERT INTO tier_unlock_conditions (tier, resource_id, min_log10)
SELECT 2, id, 3 FROM resources WHERE code = 'p';
