-- Досягнення: data-driven, одноразові умови над станом save.
-- condition_type: RESOURCE_LOG10 (потрібен resource_id), MATTER_COLLAPSES,
-- ELEMENTS_SYNTHESIZED, BROKEN_INFINITY (threshold ігнорується для BROKEN_INFINITY).

CREATE TABLE achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    condition_type VARCHAR(30) NOT NULL,
    resource_id BIGINT,
    threshold DOUBLE PRECISION NOT NULL,
    FOREIGN KEY (resource_id) REFERENCES resources(id)
);

CREATE TABLE player_achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    save_id BIGINT NOT NULL,
    achievement_id BIGINT NOT NULL,
    unlocked_at TIMESTAMP NOT NULL,
    FOREIGN KEY (save_id) REFERENCES saves(id),
    FOREIGN KEY (achievement_id) REFERENCES achievements(id),
    UNIQUE (save_id, achievement_id)
);

-- Тір 0: Пустота
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
SELECT 'first_steps', 'Перші кроки', 'Накопичити 100 енергії', 'RESOURCE_LOG10', id, 2 FROM resources WHERE code = 'E';
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
SELECT 'warming_up', 'Розігрів', 'Накопичити 1 000 000 енергії', 'RESOURCE_LOG10', id, 6 FROM resources WHERE code = 'E';
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
SELECT 'on_the_verge', 'На порозі реінкарнації', 'Досягти порогу престижу (1e25 енергії)', 'RESOURCE_LOG10', id, 25 FROM resources WHERE code = 'E';
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
SELECT 'crystal_collector', 'Колекціонер кристалів', 'Накопичити 100 кристалів пустоти', 'RESOURCE_LOG10', id, 2 FROM resources WHERE code = 'VC';
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
SELECT 'crystal_empire', 'Кристальна імперія', 'Накопичити 1 000 000 кристалів пустоти', 'RESOURCE_LOG10', id, 6 FROM resources WHERE code = 'VC';
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
SELECT 'infinity_wall', 'Стіна нескінченності', 'Досягти 1e308 енергії', 'RESOURCE_LOG10', id, 308 FROM resources WHERE code = 'E';

-- Тір 1: Матерія
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
VALUES ('broken_infinity', 'Зламана нескінченність', 'Зняти кап 1e308 енергії', 'BROKEN_INFINITY', NULL, 0);
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
VALUES ('collapse_novice', 'Колапсолог', 'Виконати колапс матерії 5 разів', 'MATTER_COLLAPSES', NULL, 5);
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
VALUES ('collapse_master', 'Майстер колапсу', 'Виконати колапс матерії 10 разів', 'MATTER_COLLAPSES', NULL, 10);
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
SELECT 'proton_stockpile', 'Протонний запас', 'Накопичити 100 протонів', 'RESOURCE_LOG10', id, 2 FROM resources WHERE code = 'p';
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
SELECT 'neutron_stockpile', 'Нейтронний запас', 'Накопичити 100 нейтронів', 'RESOURCE_LOG10', id, 2 FROM resources WHERE code = 'n';
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
SELECT 'electron_stockpile', 'Електронний запас', 'Накопичити 100 електронів', 'RESOURCE_LOG10', id, 2 FROM resources WHERE code = 'e';

-- Тір 2: Атоми
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
VALUES ('first_atom', 'Перший атом', 'Синтезувати перший елемент', 'ELEMENTS_SYNTHESIZED', NULL, 1);
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
VALUES ('junior_chemist', 'Хімік-початківець', 'Синтезувати 10 різних елементів', 'ELEMENTS_SYNTHESIZED', NULL, 10);
INSERT INTO achievements (code, name, description, condition_type, resource_id, threshold)
VALUES ('periodic_master', 'Майстер таблиці Менделєєва', 'Синтезувати всі 36 елементів', 'ELEMENTS_SYNTHESIZED', NULL, 36);
